name: images

on:
  push:
    # run only against tags
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write
  # TODO check why enabling this not able to push the image to ghcr.io
  packages: write
  # issues: write

env:
  IMAGE_REPO: ghcr.io/${{ github.repository_owner }}/snowflake-dev-tools

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_GH_ACTION_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:latest
            ${{ env.IMAGE_REPO }}:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GH_ACTION_TOKEN }}
